### ISSUE TITLE
question about transformation matrix T23

### ISSUE THREAD

**Issue by itechbear** [mike4192/spot_micro_kinematics_python#1]
Hi mike,

Thanks for your simplified yet clear code to demonstrate the kinematics of spot micro. After reading your code, I'm aligned with you that there're several typos in the original paper "Inverse Kinematic Analysis Of A Quadruped Robot". You've done a great to job to correct [T01](https://github.com/mike4192/spot_micro_kinematics_python/blob/master/utilities/spot_micro_kinematics.py#L90) and [T12](https://github.com/mike4192/spot_micro_kinematics_python/blob/master/utilities/spot_micro_kinematics.py#L121). 

However, for [T23](https://github.com/mike4192/spot_micro_kinematics_python/blob/master/utilities/spot_micro_kinematics.py#L151), I think it should be defined as following.

[ [cos, **sin**, 0, L2 cos],
  [**-sin**, cos, 0, L2 sin],
  [0, 0, 1, 0]
  [0, 0, 0, 1] ]

because the joint 3 is rotated about joint 2's z-axis towards **-y2**, so the first column of the transformation matrix should have a **negative y component**, while the second column of the transformation matrix should have two positive components.

![Leg Geometry](https://raw.githubusercontent.com/mike4192/spot_micro_kinematics_python/master/assets/general_leg_geometry.png)

I'm an entry-level learning in this area and not quite sure whether my understanding is right. Can you please help me understand it? Thank you!

**Comment by itechbear** [comment]
or is it just because theta2 is defined by inverse rotation?

**Comment by mike4192** [comment]
Hi itechbear.

I'll have to think about this more to see if you're right, but I believe the original matrix is correct as it is. The transformation to get from coordinate system 2 to 3 is a simple rotation about the z axis. 

Did you come to your conclusion by treating the angle theta 2 depicted in the diagram as a positive angle? These diagrams are not mine, just pulled straight from the paper, and they are admittedly confusing. A positive rotation about the z axis in coordinate system 2 is in the direction as specified by the right hand rule. This means that the angle theta2 shown in the diagram is a negative angle.

This library has some sample scripts I included to plot a single leg link with arbitrary angles. I encourage you to try your hypothesis with that script to see if something clicks.

**Comment by itechbear** [comment]
Yes I was looking at the pic from the paper, but forgot the right-hand rule. I'll check it again using the rule. Thank you !
